# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b28bbfbe801d69dbd3bbe7d6b11482beb8e1ed5df72eb2317de673d750379d15867042145479120ca02b4c09b2926c35375701a581cecec2328af8fa35c13512

test:
  secret_key_base: 32982728dabeffdc3c1dfc67d3e9a753cb873ba35d93f1906465d6b48d779deda31934f16279c748ea5d9a27d7ba863eb513cea09b0103c18de188e069742030

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
